name: bokrah
description: "a basic of bokrah systems"

publish_to: 'none' 


version: 3.2.0

environment:
  sdk: ^3.8.1


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2

  cupertino_icons: ^1.0.8
  get_it: ^8.0.3
  auto_updater: ^1.0.0
  http: ^1.1.0
  package_info_plus: ^4.0.0
  url_launcher: ^6.3.2
  go_router: ^16.2.1
  sqflite_common_ffi: ^2.3.6
  shared_preferences: ^2.2.2
  mobile_scanner: ^7.1.4
  flutter_bloc: ^8.1.6
  bloc: ^8.1.4
  equatable: ^2.0.5
  
dev_dependencies:
  flutter_test:
    sdk: flutter

 
  flutter_lints: ^5.0.0


flutter:

  
  uses-material-design: true
  generate: true

  